export { default as Login } from './login'
export { default as Register } from './register'
export { default as Detail } from './detail'
export { default as Create } from './create'
export { default as Links } from './links'